{
  if (mInCall) {
    fallbackToPreviousInCall(exception);
  }
 else {
    endCallOnError(exception);
  }
}
