{
  try {
    Assert.assertEquals(StorageResultCode.OperationFailedInternalError,createContainer("testCreateZeroContainer",0,"none"));
  }
 catch (  Exception e) {
    failStr(e);
  }
}
