{
  mArgs=args;
  try {
    new Backup().run();
  }
 catch (  Exception e) {
    Log.e(TAG,"Error running backup",e);
  }
  Log.d(TAG,"Finished.");
}
