{
  fail("method in NoPublicConstructorTest run unexpectedly");
}
