{
  try {
    Assert.assertEquals(StorageResultCode.OperationSucceeded,createContainer("testCreateDupContainer",4,"none"));
    Assert.assertEquals(StorageResultCode.OperationFailedInternalError,createContainer("testCreateDupContainer",4,"none"));
  }
 catch (  Exception e) {
    failStr(e);
  }
}
