{
  try {
    new Range<Integer>(null,null);
    fail("Expected exception to be thrown for (null, null)");
  }
 catch (  NullPointerException e) {
  }
  try {
    new Range<Integer>(null,0);
    fail("Expected exception to be thrown for (null, 0)");
  }
 catch (  NullPointerException e) {
  }
  try {
    new Range<Integer>(0,null);
    fail("Expected exception to be thrown for (0, null)");
  }
 catch (  NullPointerException e) {
  }
  try {
    new Range<Integer>(50,-50);
    fail("Expected exception to be thrown for (50, -50)");
  }
 catch (  IllegalArgumentException e) {
  }
  try {
    new Range<Float>(0.0f,Float.NEGATIVE_INFINITY);
    fail("Expected exception to be thrown for (0.0f, -Infinity)");
  }
 catch (  IllegalArgumentException e) {
  }
}
